### ISSUE TITLE
Multiple objects support

### ISSUE THREAD

**Issue by dmitrig01** [damballa/abracad#17]
Hey - this is a more conceptual question - would love some help here. From what I read, it looks like the following may be somehow possible, but I would love some help on how I can make this happen:

recordA.avsc:
```
{
	"type": "record",
	"name": "A",
	"fields": [ { "name": "id", "type": "long"} ]
}
```

recordB.avsc:
```
{
	"type": "record",
	"name": "B",
	"fields": [
		{ "name": "id", "type": "long" },
		{ "name": "a", "type": "A" }
	]
}
```

I.e., I would like to be able to embed A within B. Is there a preferable way to load my schemas to make this happen? I would hate to have to put the entire A object within recordB.avsc – I'm sure there's a better way.

**Comment by dmitrig01** [comment]
Ah, I see "The parse-schema function may be passed multiple schemas, in which case later schemas may reference types defined in earlier schemas".

it would be great to do this automatically though - not sure if possible - to detect a schema's dependencies so they can be loaded

**Comment by llasram** [comment]
There's been some periodic proposals to have a sort of "schema server" as part of of the core distribution which would allow this sort of automatic resolution.  I believe LinkedIn even provided an implementation, but I'm not sure of the current status. It might be worth checking out if you're motivated, but without support in the core Avro distribution I'm going to say this is out of scope for abracad.

**Comment by dmitrig01** [comment]
That's fair - I wrote something quick to do it myself :-)
