### ISSUE TITLE
Problems parsing multiple schemas

### ISSUE THREAD

**Issue by cassiomarques** [damballa/abracad#18]
Hi,

Here are the steps to reproduce the problem:

Given these two schemas:

A.json
```json
{
  "namespace": "foo.bar",
  "type": "record",
  "name": "A",
  "fields": [
    {"name": "field1", "type": "string"},
    {"name": "field2", "type": "string"}
  ]
}
```

B.json
```json
{
  "namespace": "foo.bar",
  "type": "record",
  "name": "B",
  "fields": [
    {"name": "first_field_with_type_A", "type": "A"},
    {"name": "second_field_with_type_A", "type": "A"}
  ]
}
```

When I try to load the schemas using

```clojure
(a/parse-schema "json string from A.json" "json string from B.json")
```

The returned JSON (the final schema) replaces the first occurrence of A with the correct content, but leaves the second occurrence unchanged. Like in:

```json
{
  "type":"record",
  "name":"B",
  "namespace":"foo.bar",
  "fields":[
    {"name":"first_field_with_type_A","type":{"type":"record","name":"A","fields":[{"name":"field1","type":"string"},{"name":"field2","type":"string"}]}},
    {"name":"second_field_with_type_A","type":"A"}
  ]
}
```

Shouldn't this be replacing all occurrences of "A"?

Thank you!

**Comment by llasram** [comment]
The would be some benefits to the behavior your appear to expect (some sort of lexical scope of sub-definitions), but unfortunately all definitions are global w/in the context of a given top-level schema.  So the first time `A` appears it needs to be defined, but subsequently must be referred to by that already defined name. In fact, attempting to include the definition inline a second time would result in a redefinition error, even if the "redefining" schema were identical to the previous.

If you don't think that this behavior follows Avro specification, I'd suggest opening a ticket with the upstream Avro project.

**Comment by cassiomarques** [comment]
I see, thanks for the answer!
