### ISSUE TITLE
Name-mangling makes my life hard

### ISSUE THREAD

**Issue by piranha** [damballa/abracad#20]
Hi! So the problem is that everybody needs to remember different names in different parts of system (and we have a big legacy part in Python), and name mangling makes it difficult to follow logic sometimes.

Plus I automatically convert Avro schema into Prismatic one and the libraries is not doing any changes, so it's also a bit hard. :-)

I wonder if it's possible to disable it? Maybe something like dynamic binding to turn it off/on?

**Comment by llasram** [comment]
Oh, forgot to reply to this yesterday -- apologies.  I'm not happy with the way it works now either, and I'd accept a PR for a dynamic binding (and possibly wrapper macro) for managing that behavior within a dynamic scope.  Longer-term I'd like to create a breaking interface change which moves a lot of these things into configuration on the specific DatumReader/Writer instances being created, but another dynamic var at least allowing some control seems better than nothing.

**Comment by piranha** [comment]
I guess we can further discuss that in #21. :)
